<?php

namespace AppBundle\Repository;

/**
 * CoordinateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordinateRepository extends \Doctrine\ORM\EntityRepository
{
}
